const nodemailer = require('nodemailer');   

//Importig .env here.
require('dotenv').config();

async function getMailThroughNodeMailer (fName, email, confirmationCode, html, filename, path, otp, password, csv, runcode) {
    //using nodemailer.
    let transporter =nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.EMAIL,
            pass: process.env.PASSWORD
        }
    });

    let mailOptions = {
        from: process.env.EMAIL,
        to: 'kaushal.anand@storeking.in',
    };

    if(html == 'allowed'){
        mailOptions['subject'] = 'Email confirmation for Test Case Mangement System.'
        mailOptions['html'] =  `<div>
                                     <h2>Hello ${fName} </h2>
                                     <p>
                                     Please confirm your email by clicking on the following link.
                                     </p>
                                     <a href=http://localhost:3000/user/confirm/${confirmationCode}> Click here</a>
                                     <p>your credentials are email is <b>${email}</b> and password is <b>${password}</b></p>
                                 </div>`
    }

    if(html == 'roleGeneratedPassword'){
        mailOptions['subject'] = 'New password generated by admin.'
        mailOptions['html'] =  `<div>
                                     <h2>Hello ${fName} </h2>
                                     <p>
                                     Your new password for your email :- <b>${email}</b> is <b>${password}.</b>
                                     </p>
                                 </div>`
    }

    if(html == '' ){
        mailOptions['subject'] = 'login crediential for your text case management web application.'
        mailOptions['html'] = `<div>
                                    <p>Email confirm! please go to app and login.</p>
                               </div>`;
    }

    if(html == 'forget password' ){
        mailOptions['subject'] = 'OTP to generate new password'
        mailOptions['html'] =  `<div>
                                     <h4>Dear User, </h4>
                                     <h2 style='font-weight:bold;'>OTP  is <b>${otp}</b> to login into your Test Case Management System</h2>
                                     <h4>If you did not attempted the request, please contact admin immediately.</h4>
                                </div>`
    }
                
    if (!filename == '' && !path == '') {
        mailOptions['attachments'] = [
            { filename : filename, path : path }
        ]
    }

    if(html == 'get pdf for report'){
        mailOptions['subject'] = 'Report'
        mailOptions['attachments'] = [
            { filename : filename, path : path }
        ]
    }

    if(html == 'get pdf for runlog'){
        mailOptions['subject'] = `${runcode} pdf`
        mailOptions['attachments'] = [
            { filename : filename, path : path }
        ]
    }

    if(html == 'get csv for runlog'){
        mailOptions['subject'] = `${runcode} csv`
        mailOptions['attachments'] = [
            { filename: `${filename}.csv`, content: csv }
        ]
    }

    transporter.sendMail(mailOptions , function(err, data){
        if (err) {
            console.log("Error occurs while sending the email.",err);
        } else {
            console.log('SucessFully send the mail!');
        }
    });
}

module.exports = {getMailThroughNodeMailer : getMailThroughNodeMailer};